import "../style/index.css";
import localFont from "next/font/local";
import SmoothScroll from "@/components/SmoothScroll";
import ScrollToTop from "@/components/ScrollToTop";
// import PageTransition from "@/components/PageTransition";

const clashGrotesk = localFont({
  src: [
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "Al Abir Anik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SmoothScroll>
        <ScrollToTop />
        <body
          className={`${clashGrotesk.className} antialiased bg-zinc100 text-zinc800`}
        >
          {/* leading-[130%] */}
          {/* <PageTransition> */}
          <div className="w-full px-3.75 sm:px-7.5">{children}</div>
          {/* </PageTransition> */}
        </body>
      </SmoothScroll>
    </html>
  );
}
